# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1a86e68dbb69f3b8fab7a325a5c09be4e675c7643589c4a15a778d27dbb945d6a1a4946ecdedd0353f9fa0cdaeada022f427c82fb9e548b6d64e654f00b6f1e

test:
  secret_key_base: ed2fdba8e4bb5a4fbf8b6e71fcc4360a482312bbad0172308d587e867da36e325e3a3f3556a47aca301b53418268aff66b13c75637a7402e9f5cbc48954f17c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
